apiVersion: apps/v1
kind: Deployment
metadata:
  name: elam
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template: 
    metadata:
      labels:
         app: myapp
    spec:
      containers:
      - name: c12
        image: elampari/myapp:${BUILD_NUMBER}
        resources:
          limits:
            cpu: "500m"
